# Generated by Django 4.0.3 on 2023-11-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_answer_alter_post_question_delete_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
